//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.Timekeeper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ProjectStateNamesCollection xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <DefaultActiveState>Active</DefaultActiveState>
  <DefaultPausedState>New</DefaultPausedState>
  <Projects>
    <ProjectStateNames>
      <ProjectName>Consol</ProjectName>
      <ActiveState>Active</ActiveState>
      <PausedState>Paused</PausedState>
    </ProjectStateNames>
    <ProjectStateNames>
      <ProjectName>Dan M Test Thing</ProjectName>
      <ActiveState>Active</ActiveState>
      <PausedState>Paused</PausedState>
    </ProjectStateNames>
  </Projects>
</ProjectStateNamesCollection>")]
        public global::Timekeeper.SettingsTypes.ProjectStateNamesCollection StateNameConfiguration {
            get {
                return ((global::Timekeeper.SettingsTypes.ProjectStateNamesCollection)(this["StateNameConfiguration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
        }
    }
}
