//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timekeeper.VsExtension.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                    <ProjectSettingsCollection xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
                        <DefaultActiveState>Active</DefaultActiveState>
                        <DefaultPausedState>New</DefaultPausedState>
                        <CrmConnectionString>Server=https://xrm.felinesoft.com; Username=felinesoft\Dan.Mann;Password=Wangimg1223Apr</CrmConnectionString>
                        <Whitelist>true</Whitelist>
                        <WhitelistedProjects>
                            <string>Consol</string>
                            <string>Dan M Test Thing</string>
                        </WhitelistedProjects>
                        <Projects>
                            <ProjectStateNames>
                                <ProjectName>Consol</ProjectName>
                                <ActiveState>Active</ActiveState>
                                <PausedState>Paused</PausedState>
                            </ProjectStateNames>
                            <ProjectStateNames>
                                <ProjectName>Dan M Test Thing</ProjectName>
                                <ActiveState>Active</ActiveState>
                                <PausedState>Paused</PausedState>
                            </ProjectStateNames>
                        </Projects>
                    </ProjectSettingsCollection>
                ")]
        public global::Timekeeper.SettingsTypes.ProjectSettingsCollection SettingsCollection {
            get {
                return ((global::Timekeeper.SettingsTypes.ProjectSettingsCollection)(this["SettingsCollection"]));
            }
            set {
                this["SettingsCollection"] = value;
            }
        }
    }
}
